version: '3.8'

services:
  wppbot:
    build: .
    container_name: wppconnect-bot
    volumes:
      - .:/app
      - ./tokens:/app/tokens
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "5555:5555"
    restart: always
